-- ─────────────────────────────────────────────────────────────────────────────
-- GEOGRAPHY — 27 вопросов (12 из дизайна + 15 новых)
-- ─────────────────────────────────────────────────────────────────────────────

with cat as (
    select id from public.quiz_categories where key = 'geography'
)
insert into public.quiz_questions
    (category_id, type, question_ru, question_uz, question_en, options_ru, options_uz, options_en, correct_index)
values
    -- ─── Из дизайна (12) ────────────────────────────────────────────────────
    ((select id from cat), 'multiple_choice',
        'Столица Австралии?',
        'Avstraliyaning poytaxti qaysi?',
        'What is the capital of Australia?',
        '["Сидней","Мельбурн","Канберра","Брисбен"]'::jsonb,
        '["Sidney","Melburn","Kanberra","Brisben"]'::jsonb,
        '["Sydney","Melbourne","Canberra","Brisbane"]'::jsonb, 2),

    ((select id from cat), 'multiple_choice',
        'Самая длинная река в мире?',
        'Dunyodagi eng uzun daryo qaysi?',
        'What is the longest river in the world?',
        '["Амазонка","Нил","Янцзы","Миссисипи"]'::jsonb,
        '["Amazonka","Nil","Yanszi","Missisipi"]'::jsonb,
        '["Amazon","Nile","Yangtze","Mississippi"]'::jsonb, 1),

    ((select id from cat), 'true_false',
        'Гренландия — это страна.',
        'Grenlandiya — bu davlat.',
        'Greenland is a country.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'На каком континенте находится Египет?',
        'Misr qaysi qit''ada joylashgan?',
        'On which continent is Egypt located?',
        '["Азия","Африка","Европа","Америка"]'::jsonb,
        '["Osiyo","Afrika","Yevropa","Amerika"]'::jsonb,
        '["Asia","Africa","Europe","America"]'::jsonb, 1),

    ((select id from cat), 'true_false',
        'Эверест — самая высокая гора в мире.',
        'Everest — dunyodagi eng baland tog‘.',
        'Everest is the tallest mountain in the world.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Какое море самое солёное?',
        'Qaysi dengiz eng sho‘r?',
        'Which sea is the saltiest?',
        '["Чёрное","Красное","Мёртвое","Каспийское"]'::jsonb,
        '["Qora dengiz","Qizil dengiz","O‘lik dengiz","Kaspiy dengizi"]'::jsonb,
        '["Black Sea","Red Sea","Dead Sea","Caspian Sea"]'::jsonb, 2),

    ((select id from cat), 'multiple_choice',
        'Столица Японии?',
        'Yaponiyaning poytaxti qaysi?',
        'What is the capital of Japan?',
        '["Киото","Осака","Токио","Сеул"]'::jsonb,
        '["Kioto","Osaka","Tokio","Seul"]'::jsonb,
        '["Kyoto","Osaka","Tokyo","Seoul"]'::jsonb, 2),

    ((select id from cat), 'true_false',
        'Австралия одновременно страна и континент.',
        'Avstraliya bir vaqtning o‘zida davlat ham, qit''a ham.',
        'Australia is both a country and a continent.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Сколько стран в Европейском союзе (2024)?',
        'Yevropa Ittifoqida nechta davlat bor (2024)?',
        'How many countries are in the European Union (2024)?',
        '["25","27","29","31"]'::jsonb,
        '["25","27","29","31"]'::jsonb,
        '["25","27","29","31"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'Какой океан самый большой?',
        'Eng katta okean qaysi?',
        'Which ocean is the largest?',
        '["Атлантический","Индийский","Северный Ледовитый","Тихий"]'::jsonb,
        '["Atlantika","Hind okeani","Shimoliy Muz okeani","Tinch okean"]'::jsonb,
        '["Atlantic","Indian","Arctic","Pacific"]'::jsonb, 3),

    ((select id from cat), 'true_false',
        'Байкал — самое глубокое озеро на Земле.',
        'Baykal — Yerdagi eng chuqur ko‘l.',
        'Lake Baikal is the deepest lake on Earth.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Какая страна имеет форму сапога?',
        'Qaysi davlat etik shaklida?',
        'Which country is shaped like a boot?',
        '["Греция","Италия","Испания","Португалия"]'::jsonb,
        '["Gretsiya","Italiya","Ispaniya","Portugaliya"]'::jsonb,
        '["Greece","Italy","Spain","Portugal"]'::jsonb, 1),

    -- ─── Новые 15 ───────────────────────────────────────────────────────────
    ((select id from cat), 'multiple_choice',
        'Столица Узбекистана?',
        'O‘zbekistonning poytaxti qaysi?',
        'What is the capital of Uzbekistan?',
        '["Самарканд","Ташкент","Бухара","Наманган"]'::jsonb,
        '["Samarqand","Toshkent","Buxoro","Namangan"]'::jsonb,
        '["Samarkand","Tashkent","Bukhara","Namangan"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'Сколько континентов на Земле?',
        'Yer yuzida nechta qit''a bor?',
        'How many continents are there on Earth?',
        '["5","6","7","8"]'::jsonb, '["5","6","7","8"]'::jsonb, '["5","6","7","8"]'::jsonb, 2),

    ((select id from cat), 'true_false',
        'Сахара — самая большая пустыня в мире.',
        'Sahroyi Kabir — dunyodagi eng katta cho‘l.',
        'The Sahara is the largest desert in the world.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'Столица Франции?',
        'Fransiyaning poytaxti qaysi?',
        'What is the capital of France?',
        '["Марсель","Лион","Париж","Ницца"]'::jsonb,
        '["Marsel","Lion","Parij","Nitsa"]'::jsonb,
        '["Marseille","Lyon","Paris","Nice"]'::jsonb, 2),

    ((select id from cat), 'multiple_choice',
        'Самая большая страна в мире по площади?',
        'Maydoni bo‘yicha dunyodagi eng katta davlat qaysi?',
        'The largest country by area is:',
        '["Китай","США","Канада","Россия"]'::jsonb,
        '["Xitoy","AQSh","Kanada","Rossiya"]'::jsonb,
        '["China","USA","Canada","Russia"]'::jsonb, 3),

    ((select id from cat), 'true_false',
        'Антарктида — самый холодный континент.',
        'Antarktida — eng sovuq qit''a.',
        'Antarctica is the coldest continent.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Какой пролив отделяет Европу от Африки?',
        'Yevropani Afrikadan qaysi bo‘g‘oz ajratib turadi?',
        'Which strait separates Europe from Africa?',
        '["Босфор","Гибралтар","Ла-Манш","Берингов"]'::jsonb,
        '["Bosfor","Jabalitoriq","La-Mansh","Bering"]'::jsonb,
        '["Bosphorus","Gibraltar","English Channel","Bering"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'В какой стране находится Тадж-Махал?',
        'Toj-Mahal qaysi davlatda joylashgan?',
        'The Taj Mahal is located in:',
        '["Пакистан","Индия","Иран","Бангладеш"]'::jsonb,
        '["Pokiston","Hindiston","Eron","Bangladesh"]'::jsonb,
        '["Pakistan","India","Iran","Bangladesh"]'::jsonb, 1),

    ((select id from cat), 'true_false',
        'Африка — второй по величине континент.',
        'Afrika — kattalik bo‘yicha ikkinchi qit''a.',
        'Africa is the second-largest continent.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Какая столица расположена на двух континентах?',
        'Qaysi poytaxt ikki qit''ada joylashgan?',
        'Which capital city straddles two continents?',
        '["Москва","Каир","Стамбул","Афины"]'::jsonb,
        '["Moskva","Qohira","Istanbul","Afina"]'::jsonb,
        '["Moscow","Cairo","Istanbul","Athens"]'::jsonb, 2),

    ((select id from cat), 'multiple_choice',
        'Самая высокая вершина Африки?',
        'Afrikaning eng baland cho‘qqisi qaysi?',
        'The highest peak in Africa is:',
        '["Кения","Килиманджаро","Стэнли","Маргерита"]'::jsonb,
        '["Keniya","Kilimanjaro","Stenli","Margerita"]'::jsonb,
        '["Mount Kenya","Kilimanjaro","Stanley","Margherita"]'::jsonb, 1),

    ((select id from cat), 'true_false',
        'Амазонка протекает через Бразилию.',
        'Amazonka Braziliya orqali oqib o‘tadi.',
        'The Amazon River flows through Brazil.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'В какой стране находится Великая Китайская стена?',
        'Buyuk Xitoy devori qaysi davlatda joylashgan?',
        'In which country is the Great Wall?',
        '["Япония","Корея","Китай","Монголия"]'::jsonb,
        '["Yaponiya","Koreya","Xitoy","Mongoliya"]'::jsonb,
        '["Japan","Korea","China","Mongolia"]'::jsonb, 2),

    ((select id from cat), 'multiple_choice',
        'Какое государство самое маленькое в мире?',
        'Dunyodagi eng kichik davlat qaysi?',
        'The smallest country in the world is:',
        '["Монако","Сан-Марино","Ватикан","Лихтенштейн"]'::jsonb,
        '["Monako","San-Marino","Vatikan","Lixtenshteyn"]'::jsonb,
        '["Monaco","San Marino","Vatican","Liechtenstein"]'::jsonb, 2),

    ((select id from cat), 'true_false',
        'Тихий океан больше всех материков вместе взятых.',
        'Tinch okean barcha qit''alar maydonidan ham katta.',
        'The Pacific Ocean is larger than all continents combined.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Сколько часовых поясов в России?',
        'Rossiyada nechta soat mintaqasi bor?',
        'How many time zones does Russia span?',
        '["7","9","11","13"]'::jsonb,
        '["7","9","11","13"]'::jsonb,
        '["7","9","11","13"]'::jsonb, 2);
