-- ─────────────────────────────────────────────────────────────────────────────
-- HISTORY — 26 вопросов (11 из дизайна + 15 новых)
-- ─────────────────────────────────────────────────────────────────────────────

with cat as (
    select id from public.quiz_categories where key = 'history'
)
insert into public.quiz_questions
    (category_id, type, question_ru, question_uz, question_en, options_ru, options_uz, options_en, correct_index)
values
    -- ─── Из дизайна (11) ────────────────────────────────────────────────────
    ((select id from cat), 'multiple_choice',
        'В каком году началась Вторая мировая война?',
        'Ikkinchi jahon urushi qaysi yilda boshlangan?',
        'In what year did World War II start?',
        '["1937","1939","1941","1945"]'::jsonb,
        '["1937","1939","1941","1945"]'::jsonb,
        '["1937","1939","1941","1945"]'::jsonb, 1),

    ((select id from cat), 'true_false',
        'Юрий Гагарин — первый человек в космосе.',
        'Yuriy Gagarin — kosmosga uchgan birinchi inson.',
        'Yuri Gagarin was the first human in space.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Кто был первым императором Рима?',
        'Rimning birinchi imperatori kim edi?',
        'Who was the first Roman emperor?',
        '["Цезарь","Август","Нерон","Тиберий"]'::jsonb,
        '["Sezar","Avgust","Neron","Tiberiy"]'::jsonb,
        '["Caesar","Augustus","Nero","Tiberius"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'В каком веке пала Берлинская стена?',
        'Berlin devori qaysi asrda qulagan?',
        'In which century did the Berlin Wall fall?',
        '["XVIII","XIX","XX","XXI"]'::jsonb,
        '["XVIII","XIX","XX","XXI"]'::jsonb,
        '["XVIII","XIX","XX","XXI"]'::jsonb, 2),

    ((select id from cat), 'true_false',
        'Пирамиды в Гизе старше Стоунхенджа.',
        'Giza piramidalari Stounxenjdan ko‘ra qadimiyroq.',
        'The Giza Pyramids are older than Stonehenge.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Какая династия правила Китаем дольше всех?',
        'Xitoyni eng uzoq vaqt davomida boshqargan sulola qaysi?',
        'Which dynasty ruled China the longest?',
        '["Мин","Тан","Цин","Хань"]'::jsonb,
        '["Min","Tan","Sin","Xan"]'::jsonb,
        '["Ming","Tang","Qing","Han"]'::jsonb, 3),

    ((select id from cat), 'multiple_choice',
        'Кто открыл Америку для Европы в 1492?',
        '1492-yilda Amerikani Yevropa uchun kim kashf etgan?',
        'Who reached the Americas for Europe in 1492?',
        '["Магеллан","Колумб","Веспуччи","Кук"]'::jsonb,
        '["Magellan","Kolumb","Vespuchchi","Kuk"]'::jsonb,
        '["Magellan","Columbus","Vespucci","Cook"]'::jsonb, 1),

    ((select id from cat), 'true_false',
        'Наполеон был ростом меньше 1.5 м.',
        'Napoleonning bo‘yi 1.5 metrdan past bo‘lgan.',
        'Napoleon was shorter than 1.5 m.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'В каком году распался СССР?',
        'Sovet Ittifoqi qaysi yilda parchalangan?',
        'In what year did the Soviet Union dissolve?',
        '["1989","1990","1991","1993"]'::jsonb,
        '["1989","1990","1991","1993"]'::jsonb,
        '["1989","1990","1991","1993"]'::jsonb, 2),

    ((select id from cat), 'multiple_choice',
        'Какая стена видна из космоса (по легенде)?',
        'Afsonaga ko‘ra, qaysi devor kosmosdan ko‘rinadi?',
        'Which wall is "visible from space" according to legend?',
        '["Адрианов вал","Великая Китайская","Берлинская","Иерусалимская"]'::jsonb,
        '["Adrian devori","Buyuk Xitoy devori","Berlin devori","Quddus devori"]'::jsonb,
        '["Hadrian''s Wall","Great Wall of China","Berlin Wall","Jerusalem Wall"]'::jsonb, 1),

    ((select id from cat), 'true_false',
        'Клеопатра жила ближе к нашему времени, чем к строительству пирамид.',
        'Kleopatra piramidalar qurilishidan ko‘ra bizning davrimizga yaqinroq yashagan.',
        'Cleopatra lived closer to our time than to the building of the pyramids.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    -- ─── Новые 15 ───────────────────────────────────────────────────────────
    ((select id from cat), 'multiple_choice',
        'Кто был основателем империи Тимуридов?',
        'Temuriylar sulolasining asoschisi kim edi?',
        'Who founded the Timurid Empire?',
        '["Чингисхан","Амир Тимур","Бабур","Улугбек"]'::jsonb,
        '["Chingizxon","Amir Temur","Bobur","Ulug‘bek"]'::jsonb,
        '["Genghis Khan","Amir Timur","Babur","Ulugh Beg"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'В каком году началась Первая мировая война?',
        'Birinchi jahon urushi qaysi yilda boshlangan?',
        'In what year did World War I begin?',
        '["1905","1912","1914","1918"]'::jsonb,
        '["1905","1912","1914","1918"]'::jsonb,
        '["1905","1912","1914","1918"]'::jsonb, 2),

    ((select id from cat), 'true_false',
        'Авраам Линкольн был 16-м президентом США.',
        'Avraam Linkoln AQShning 16-prezidenti bo‘lgan.',
        'Abraham Lincoln was the 16th US president.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Где была изобретена бумага?',
        'Qog‘oz qaerda ixtiro qilingan?',
        'Where was paper invented?',
        '["Египет","Греция","Китай","Индия"]'::jsonb,
        '["Misr","Gretsiya","Xitoy","Hindiston"]'::jsonb,
        '["Egypt","Greece","China","India"]'::jsonb, 2),

    ((select id from cat), 'multiple_choice',
        'Кто написал «Манифест Коммунистической партии»?',
        '"Kommunistik partiya manifesti"ni kim yozgan?',
        'Who wrote The Communist Manifesto?',
        '["Ленин","Сталин","Маркс и Энгельс","Троцкий"]'::jsonb,
        '["Lenin","Stalin","Marks va Engels","Trotskiy"]'::jsonb,
        '["Lenin","Stalin","Marx and Engels","Trotsky"]'::jsonb, 2),

    ((select id from cat), 'true_false',
        'Революция в России произошла в 1917 году.',
        'Rossiyada inqilob 1917-yilda yuz bergan.',
        'The Russian Revolution happened in 1917.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'В какой стране родилась демократия?',
        'Demokratiya qaysi davlatda paydo bo‘lgan?',
        'In which country was democracy born?',
        '["Рим","Греция","Египет","Персия"]'::jsonb,
        '["Rim","Gretsiya","Misr","Eron"]'::jsonb,
        '["Rome","Greece","Egypt","Persia"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'Кто был первым человеком на Луне?',
        'Oyga qadam qo‘ygan birinchi inson kim?',
        'Who was the first human on the Moon?',
        '["Олдрин","Армстронг","Гагарин","Гленн"]'::jsonb,
        '["Oldrin","Armstrong","Gagarin","Glenn"]'::jsonb,
        '["Aldrin","Armstrong","Gagarin","Glenn"]'::jsonb, 1),

    ((select id from cat), 'true_false',
        'Османская империя пала после Первой мировой войны.',
        'Usmonli imperiyasi Birinchi jahon urushidan keyin parchalangan.',
        'The Ottoman Empire fell after WWI.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Кто был автором «Бабурнамы»?',
        '"Boburnoma" asarining muallifi kim?',
        'Who wrote the "Baburnama"?',
        '["Алишер Навои","Захир ад-дин Бабур","Улугбек","Хорезми"]'::jsonb,
        '["Alisher Navoiy","Zahiriddin Muhammad Bobur","Ulug‘bek","Xorazmiy"]'::jsonb,
        '["Alisher Navoi","Babur","Ulugh Beg","Al-Khwarizmi"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'В каком году человек впервые полетел в космос?',
        'Inson qaysi yilda birinchi marta kosmosga uchgan?',
        'In what year did humans first fly to space?',
        '["1957","1959","1961","1969"]'::jsonb,
        '["1957","1959","1961","1969"]'::jsonb,
        '["1957","1959","1961","1969"]'::jsonb, 2),

    ((select id from cat), 'true_false',
        'Великая французская революция началась в 1789 году.',
        'Buyuk fransuz inqilobi 1789-yilda boshlangan.',
        'The French Revolution began in 1789.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Кто построил обсерваторию в Самарканде в XV веке?',
        'XV asrda Samarqandda rasadxonani kim qurdirgan?',
        'Who built the 15th-century observatory in Samarkand?',
        '["Амир Тимур","Улугбек","Бабур","Шейбани"]'::jsonb,
        '["Amir Temur","Ulug‘bek","Bobur","Shayboniy"]'::jsonb,
        '["Amir Timur","Ulugh Beg","Babur","Sheybani"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'Какой народ построил Мачу-Пикчу?',
        'Machu-Pikchuni qaysi xalq qurgan?',
        'Which people built Machu Picchu?',
        '["Майя","Ацтеки","Инки","Ольмеки"]'::jsonb,
        '["Mayya","Aslteklar","Inklar","Olmeklar"]'::jsonb,
        '["Maya","Aztecs","Inca","Olmec"]'::jsonb, 2),

    ((select id from cat), 'true_false',
        'Хиросима была атакована атомной бомбой в 1945.',
        'Xirosima 1945-yilda atom bombasi bilan zarbaga uchragan.',
        'Hiroshima was hit by an atomic bomb in 1945.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0);
