-- ─────────────────────────────────────────────────────────────────────────────
-- CINEMA — 26 вопросов (11 из дизайна + 15 новых)
-- ─────────────────────────────────────────────────────────────────────────────

with cat as (
    select id from public.quiz_categories where key = 'cinema'
)
insert into public.quiz_questions
    (category_id, type, question_ru, question_uz, question_en, options_ru, options_uz, options_en, correct_index)
values
    -- ─── Из дизайна (11) ────────────────────────────────────────────────────
    ((select id from cat), 'multiple_choice',
        'Кто режиссёр «Криминального чтива»?',
        '"Pulp Fiction" filmining rejissyori kim?',
        'Who directed Pulp Fiction?',
        '["Скорсезе","Тарантино","Нолан","Финчер"]'::jsonb,
        '["Skorseze","Tarantino","Nolan","Fincher"]'::jsonb,
        '["Scorsese","Tarantino","Nolan","Fincher"]'::jsonb, 1),

    ((select id from cat), 'true_false',
        'Фильм «Титаник» получил 11 «Оскаров».',
        '"Titanik" filmi 11 ta "Oskar" mukofotini olgan.',
        'The film Titanic won 11 Oscars.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Какой студии принадлежит Marvel?',
        'Marvel qaysi kompaniyaga tegishli?',
        'Which studio owns Marvel?',
        '["Warner Bros.","Disney","Sony","Universal"]'::jsonb,
        '["Warner Bros.","Disney","Sony","Universal"]'::jsonb,
        '["Warner Bros.","Disney","Sony","Universal"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'Как зовут главного героя «Гарри Поттера»?',
        '"Garri Potter"ning bosh qahramoni kim?',
        'Who is the main character of Harry Potter?',
        '["Рон","Гарри","Невилл","Драко"]'::jsonb,
        '["Ron","Garri","Nevill","Drako"]'::jsonb,
        '["Ron","Harry","Neville","Draco"]'::jsonb, 1),

    ((select id from cat), 'true_false',
        'В «Звёздных войнах» Дарт Вейдер — отец Люка.',
        '"Yulduzli urushlar" filmida Dart Veyder Lyukning otasi.',
        'In Star Wars, Darth Vader is Luke''s father.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Кто сыграл Джокера в «Тёмном рыцаре» (2008)?',
        '"Qora ritsar" (2008) filmida Jokerni kim o‘ynagan?',
        'Who played the Joker in The Dark Knight (2008)?',
        '["Хоакин Феникс","Хит Леджер","Джаред Лето","Джек Николсон"]'::jsonb,
        '["Xoakin Feniks","Xit Lejer","Jared Leto","Jek Nikolson"]'::jsonb,
        '["Joaquin Phoenix","Heath Ledger","Jared Leto","Jack Nicholson"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'Сколько частей основной саги «Звёздных войн»?',
        '"Yulduzli urushlar" asosiy sagasi nechta qismdan iborat?',
        'How many episodes are in the main Star Wars saga?',
        '["6","9","10","12"]'::jsonb, '["6","9","10","12"]'::jsonb, '["6","9","10","12"]'::jsonb, 1),

    ((select id from cat), 'true_false',
        'Сериал «Друзья» снимался в Нью-Йорке.',
        '"Do‘stlar" seriali Nyu-Yorkda suratga olingan.',
        'The TV series "Friends" was filmed in New York.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'Какой фильм Pixar вышел первым?',
        'Pixar studiyasining birinchi filmi qaysi?',
        'Which Pixar film was released first?',
        '["В поисках Немо","Корпорация монстров","История игрушек","Тачки"]'::jsonb,
        '["Nemoni qidirib","Maxluqlar korporatsiyasi","O‘yinchoqlar tarixi","Mashinalar"]'::jsonb,
        '["Finding Nemo","Monsters, Inc.","Toy Story","Cars"]'::jsonb, 2),

    ((select id from cat), 'multiple_choice',
        'Кто режиссёр «Начала» и «Интерстеллара»?',
        '"Boshlanish" va "Interstellar" filmlarining rejissyori kim?',
        'Who directed Inception and Interstellar?',
        '["Спилберг","Нолан","Виллёнев","Камерон"]'::jsonb,
        '["Spilberg","Nolan","Villyonev","Kameron"]'::jsonb,
        '["Spielberg","Nolan","Villeneuve","Cameron"]'::jsonb, 1),

    ((select id from cat), 'true_false',
        '«Властелин колец» снимался в Новой Зеландии.',
        '"Uzuklar hukmdori" filmi Yangi Zelandiyada suratga olingan.',
        'The Lord of the Rings was filmed in New Zealand.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    -- ─── Новые 15 ───────────────────────────────────────────────────────────
    ((select id from cat), 'multiple_choice',
        'Кто режиссёр фильма «Аватар»?',
        '"Avatar" filmining rejissyori kim?',
        'Who directed Avatar?',
        '["Спилберг","Кэмерон","Лукас","Финчер"]'::jsonb,
        '["Spilberg","Kameron","Lukas","Fincher"]'::jsonb,
        '["Spielberg","Cameron","Lucas","Fincher"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'В каком году вышел первый «Терминатор»?',
        'Birinchi "Terminator" qaysi yilda chiqqan?',
        'In what year was the first Terminator released?',
        '["1981","1984","1986","1991"]'::jsonb,
        '["1981","1984","1986","1991"]'::jsonb,
        '["1981","1984","1986","1991"]'::jsonb, 1),

    ((select id from cat), 'true_false',
        '«Мстители: Финал» — самый кассовый фильм в истории (на 2024).',
        '"Qasoskorlar: Final" — 2024-yilgacha eng katta daromad olgan film.',
        'Avengers: Endgame was the highest-grossing film by 2024.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'Кто сыграл Форреста Гампа?',
        'Forrest Gampni kim o‘ynagan?',
        'Who played Forrest Gump?',
        '["Том Хэнкс","Том Круз","Кевин Костнер","Мел Гибсон"]'::jsonb,
        '["Tom Xenks","Tom Kruz","Kevin Kostner","Mel Gibson"]'::jsonb,
        '["Tom Hanks","Tom Cruise","Kevin Costner","Mel Gibson"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Какая студия выпустила «Король Лев»?',
        '"Sher qiroli" filmini qaysi studiya chiqargan?',
        'Which studio released The Lion King?',
        '["Pixar","Disney","DreamWorks","Universal"]'::jsonb,
        '["Pixar","Disney","DreamWorks","Universal"]'::jsonb,
        '["Pixar","Disney","DreamWorks","Universal"]'::jsonb, 1),

    ((select id from cat), 'true_false',
        '«Властелин колец: Возвращение короля» получил 11 «Оскаров».',
        '"Uzuklar hukmdori: Qirolning qaytishi" 11 ta "Oskar" mukofotini olgan.',
        'The Return of the King won 11 Oscars.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Кто режиссёр «Челюстей»?',
        '"Akula" filmining rejissyori kim?',
        'Who directed Jaws?',
        '["Лукас","Скорсезе","Спилберг","Кубрик"]'::jsonb,
        '["Lukas","Skorseze","Spilberg","Kubrik"]'::jsonb,
        '["Lucas","Scorsese","Spielberg","Kubrick"]'::jsonb, 2),

    ((select id from cat), 'multiple_choice',
        'Кто озвучил Вуди в «Истории игрушек»?',
        '"O‘yinchoqlar tarixi"da Vudi rolini kim ovoz bergan?',
        'Who voiced Woody in Toy Story?',
        '["Том Хэнкс","Тим Аллен","Билли Кристал","Эдди Мёрфи"]'::jsonb,
        '["Tom Xenks","Tim Allen","Billi Kristal","Eddi Myorfi"]'::jsonb,
        '["Tom Hanks","Tim Allen","Billy Crystal","Eddie Murphy"]'::jsonb, 0),

    ((select id from cat), 'true_false',
        '«Игра престолов» основана на книгах Дж. Р. Р. Мартина.',
        '"Taxtlar o‘yini" J. R. R. Martin kitoblari asosida olingan.',
        'Game of Thrones is based on books by G. R. R. Martin.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Какой актёр играет Шерлока Холмса в BBC-сериале «Шерлок»?',
        'BBC "Sherlock" serialida Sherlok Xolms rolini kim o‘ynaydi?',
        'Who plays Sherlock Holmes in BBC''s Sherlock?',
        '["Хью Лори","Бенедикт Камбербэтч","Мартин Фриман","Том Хиддлстон"]'::jsonb,
        '["Xyu Lori","Benedikt Kamberbetch","Martin Friman","Tom Xiddlston"]'::jsonb,
        '["Hugh Laurie","Benedict Cumberbatch","Martin Freeman","Tom Hiddleston"]'::jsonb, 1),

    ((select id from cat), 'multiple_choice',
        'Кто режиссёр «Криминальной фильмы»? (Goodfellas, 1990)',
        '"Goodfellas" (1990) filmining rejissyori kim?',
        'Who directed Goodfellas (1990)?',
        '["Спилберг","Скорсезе","Тарантино","Коппола"]'::jsonb,
        '["Spilberg","Skorseze","Tarantino","Koppola"]'::jsonb,
        '["Spielberg","Scorsese","Tarantino","Coppola"]'::jsonb, 1),

    ((select id from cat), 'true_false',
        '«Матрица» вышла в 1999 году.',
        '"Matritsa" 1999-yilda chiqqan.',
        'The Matrix was released in 1999.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0),

    ((select id from cat), 'multiple_choice',
        'Кто играет Тони Старка в Marvel?',
        'Marvelda Toni Stark rolini kim o‘ynaydi?',
        'Who plays Tony Stark in Marvel films?',
        '["Крис Эванс","Крис Хемсворт","Роберт Дауни-мл.","Марк Руффало"]'::jsonb,
        '["Kris Evans","Kris Xemsvort","Robert Dauni-kichik","Mark Ruffalo"]'::jsonb,
        '["Chris Evans","Chris Hemsworth","Robert Downey Jr.","Mark Ruffalo"]'::jsonb, 2),

    ((select id from cat), 'multiple_choice',
        'Какой фильм получил «Оскар» за лучший фильм 2020?',
        '2020-yilgi "Eng yaxshi film" "Oskar"ini qaysi film olgan?',
        'Which film won Best Picture at the 2020 Oscars?',
        '["1917","Джокер","Паразиты","Ирландец"]'::jsonb,
        '["1917","Joker","Parazitlar","Irlandiyalik"]'::jsonb,
        '["1917","Joker","Parasite","The Irishman"]'::jsonb, 2),

    ((select id from cat), 'true_false',
        '«Унесённые призраками» — японский мультфильм Хаяо Миядзаки.',
        '"Sehrli ruhlar" — Xayao Miyadzakining yapon multfilmi.',
        '"Spirited Away" is a Japanese animated film by Hayao Miyazaki.',
        '["Правда","Ложь"]'::jsonb, '["Rost","Yolg‘on"]'::jsonb, '["True","False"]'::jsonb, 0);
